### ISSUE TITLE
Warning about react versions when using this in a non-react repo

### ISSUE THREAD

**Issue by joshuavial** [enspiral-dev-academy/eslint-plugin-eda#1]
Would be great to use this config in repos which don't have react. It currently works but gives a warning

`Warning: React version was set to "detect" in eslint-plugin-react settings, but the "react" package is not installed. Assuming latest React version for linting.`

I would love to find a way to disable this warning or to opt out of extending react as needed.

**Comment by gerardpaapu** [comment]
it might be cleaner to export different configs from the same package, e.g. `eda/react`, `eda/fullstack` or whatever

**Comment by gerardpaapu** [comment]
We now provide `eda` and `eda/react`
